In [13]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [14]:
dataset = pd.read_csv('Data.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [15]:
print(X)

[['Linda' nan 139.0]
 ['Wuri' 55.0 163.0]
 ['Rahayu' 53.0 172.0]
 ['Intan' 58.0 nan]
 ['Jeje' 62.0 148.0]
 ['Yola' 70.0 172.0]
 ['Rovi' 52.0 171.0]
 ['Azel' nan 172.0]
 ['Natalia' 67.0 172.0]
 ['Karyn' 62.0 166.0]]


In [16]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [17]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

In [18]:
print(X)

[['Linda' 59.875 139.0]
 ['Wuri' 55.0 163.0]
 ['Rahayu' 53.0 172.0]
 ['Intan' 58.0 163.88888888888889]
 ['Jeje' 62.0 148.0]
 ['Yola' 70.0 172.0]
 ['Rovi' 52.0 171.0]
 ['Azel' 59.875 172.0]
 ['Natalia' 67.0 172.0]
 ['Karyn' 62.0 166.0]]


In [19]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = ct.fit_transform(X)

In [20]:
print(X)

  (0, 4)	1.0
  (0, 10)	59.875
  (0, 11)	139.0
  (1, 8)	1.0
  (1, 10)	55.0
  (1, 11)	163.0
  (2, 6)	1.0
  (2, 10)	53.0
  (2, 11)	172.0
  (3, 1)	1.0
  (3, 10)	58.0
  (3, 11)	163.88888888888889
  (4, 2)	1.0
  (4, 10)	62.0
  (4, 11)	148.0
  (5, 9)	1.0
  (5, 10)	70.0
  (5, 11)	172.0
  (6, 7)	1.0
  (6, 10)	52.0
  (6, 11)	171.0
  (7, 0)	1.0
  (7, 10)	59.875
  (7, 11)	172.0
  (8, 5)	1.0
  (8, 10)	67.0
  (8, 11)	172.0
  (9, 3)	1.0
  (9, 10)	62.0
  (9, 11)	166.0


In [21]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [22]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


In [23]:
from sklearn.model_selection import train_test_split
X = X.toarray()
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [24]:
print(X_train)

[[  0.           0.           0.           0.           0.
    0.           0.           1.           0.           0.
   52.         171.        ]
 [  0.           0.           1.           0.           0.
    0.           0.           0.           0.           0.
   62.         148.        ]
 [  0.           0.           0.           0.           1.
    0.           0.           0.           0.           0.
   59.875      139.        ]
 [  0.           1.           0.           0.           0.
    0.           0.           0.           0.           0.
   58.         163.88888889]
 [  0.           0.           0.           0.           0.
    0.           0.           0.           1.           0.
   55.         163.        ]
 [  1.           0.           0.           0.           0.
    0.           0.           0.           0.           0.
   59.875      172.        ]
 [  0.           0.           0.           0.           0.
    1.           0.           0.           0.           0.


In [25]:
print(X_test)

[[  0.   0.   0.   0.   0.   0.   1.   0.   0.   0.  53. 172.]
 [  0.   0.   0.   1.   0.   0.   0.   0.   0.   0.  62. 166.]]


In [26]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [27]:
print(y_test)

[0 1]


In [28]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
X_test[:, 3:] = sc.transform(X_test[:, 3:])

In [29]:
print(X_train)

[[ 0.          0.          0.          0.         -0.37796447 -0.37796447
   0.          2.64575131 -0.37796447 -0.37796447 -1.53259069  0.71295453]
 [ 0.          0.          1.          0.         -0.37796447 -0.37796447
   0.         -0.37796447 -0.37796447 -0.37796447  0.27711049 -1.24176849]
 [ 0.          0.          0.          0.          2.64575131 -0.37796447
   0.         -0.37796447 -0.37796447 -0.37796447 -0.10745101 -2.00666011]
 [ 0.          1.          0.          0.         -0.37796447 -0.37796447
   0.         -0.37796447 -0.37796447 -0.37796447 -0.44676998  0.10859572]
 [ 0.          0.          0.          0.         -0.37796447 -0.37796447
   0.         -0.37796447  2.64575131 -0.37796447 -0.98968034  0.03305087]
 [ 1.          0.          0.          0.         -0.37796447 -0.37796447
   0.         -0.37796447 -0.37796447 -0.37796447 -0.10745101  0.79794249]
 [ 0.          0.          0.          0.         -0.37796447  2.64575131
   0.         -0.37796447 -0.377

In [30]:
print(X_test)

[[ 0.          0.          0.          0.         -0.37796447 -0.37796447
   1.         -0.37796447 -0.37796447 -0.37796447 -1.35162057  0.79794249]
 [ 0.          0.          0.          1.         -0.37796447 -0.37796447
   0.         -0.37796447 -0.37796447 -0.37796447  0.27711049  0.28801475]]
